import {
  configureFonts,
  MD3DarkTheme,
  MD3LightTheme,
} from "react-native-paper";

const fontConfig = {
  displayLarge: {
    fontFamily: "System",
    fontSize: 32,
    fontWeight: "400" as const,
    letterSpacing: 0,
    lineHeight: 40,
  },
  displayMedium: {
    fontFamily: "System",
    fontSize: 28,
    fontWeight: "400" as const,
    letterSpacing: 0,
    lineHeight: 36,
  },
  displaySmall: {
    fontFamily: "System",
    fontSize: 24,
    fontWeight: "400" as const,
    letterSpacing: 0,
    lineHeight: 32,
  },
  headlineLarge: {
    fontFamily: "System",
    fontSize: 22,
    fontWeight: "600" as const,
    letterSpacing: 0,
    lineHeight: 28,
  },
  headlineMedium: {
    fontFamily: "System",
    fontSize: 20,
    fontWeight: "600" as const,
    letterSpacing: 0,
    lineHeight: 26,
  },
  headlineSmall: {
    fontFamily: "System",
    fontSize: 18,
    fontWeight: "600" as const,
    letterSpacing: 0,
    lineHeight: 24,
  },
  titleLarge: {
    fontFamily: "System",
    fontSize: 16,
    fontWeight: "600" as const,
    letterSpacing: 0,
    lineHeight: 22,
  },
  titleMedium: {
    fontFamily: "System",
    fontSize: 14,
    fontWeight: "600" as const,
    letterSpacing: 0,
    lineHeight: 20,
  },
  titleSmall: {
    fontFamily: "System",
    fontSize: 12,
    fontWeight: "600" as const,
    letterSpacing: 0,
    lineHeight: 18,
  },
  bodyLarge: {
    fontFamily: "System",
    fontSize: 16,
    fontWeight: "400" as const,
    letterSpacing: 0,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: "System",
    fontSize: 14,
    fontWeight: "400" as const,
    letterSpacing: 0,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: "System",
    fontSize: 12,
    fontWeight: "400" as const,
    letterSpacing: 0,
    lineHeight: 16,
  },
  labelLarge: {
    fontFamily: "System",
    fontSize: 14,
    fontWeight: "500" as const,
    letterSpacing: 0,
    lineHeight: 20,
  },
  labelMedium: {
    fontFamily: "System",
    fontSize: 12,
    fontWeight: "500" as const,
    letterSpacing: 0,
    lineHeight: 16,
  },
  labelSmall: {
    fontFamily: "System",
    fontSize: 11,
    fontWeight: "500" as const,
    letterSpacing: 0,
    lineHeight: 14,
  },
};

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: "#ff6b6b",
    primaryContainer: "#ffe0e0",
    secondary: "#4a5568",
    secondaryContainer: "#e2e8f0",
    tertiary: "#38a169",
    tertiaryContainer: "#d4f8e8",
    background: "#f5f5f5",
    surface: "#ffffff",
    surfaceVariant: "#f8f8f8",
    error: "#dc2626",
    errorContainer: "#fee2e2",
    onPrimary: "#ffffff",
    onPrimaryContainer: "#7f1d1d",
    onSecondary: "#ffffff",
    onSecondaryContainer: "#1a202c",
    onTertiary: "#ffffff",
    onTertiaryContainer: "#065f46",
    onBackground: "#1a1a1a",
    onSurface: "#1a1a1a",
    onSurfaceVariant: "#4a5568",
    onError: "#ffffff",
    onErrorContainer: "#7f1d1d",
    outline: "#e0e0e0",
    outlineVariant: "#f0f0f0",
    inverseSurface: "#2d3748",
    inverseOnSurface: "#f7fafc",
    inversePrimary: "#ff9999",
    elevation: {
      level0: "transparent",
      level1: "#ffffff",
      level2: "#fafafa",
      level3: "#f8f8f8",
      level4: "#f5f5f5",
      level5: "#f0f0f0",
    },
  },
  fonts: configureFonts({ config: fontConfig }),
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: "#ff9999",
    primaryContainer: "#7f3333",
    secondary: "#cbd5e0",
    secondaryContainer: "#2d3748",
    tertiary: "#68d391",
    tertiaryContainer: "#2f855a",
    background: "#1a1a1a",
    surface: "#2d2d2d",
    surfaceVariant: "#3a3a3a",
    error: "#f87171",
    errorContainer: "#7f1d1d",
    onPrimary: "#1a1a1a",
    onPrimaryContainer: "#ffe0e0",
    onSecondary: "#1a202c",
    onSecondaryContainer: "#e2e8f0",
    onTertiary: "#065f46",
    onTertiaryContainer: "#d4f8e8",
    onBackground: "#f5f5f5",
    onSurface: "#f5f5f5",
    onSurfaceVariant: "#cbd5e0",
    onError: "#1a1a1a",
    onErrorContainer: "#fee2e2",
    outline: "#4a4a4a",
    outlineVariant: "#3a3a3a",
    inverseSurface: "#e2e8f0",
    inverseOnSurface: "#1a202c",
    inversePrimary: "#ff6b6b",
    elevation: {
      level0: "transparent",
      level1: "#2d2d2d",
      level2: "#3a3a3a",
      level3: "#424242",
      level4: "#4a4a4a",
      level5: "#525252",
    },
  },
  fonts: configureFonts({ config: fontConfig }),
};
